# 异常处理

## 7.1 异常概述与异常体系结构

Error：Java虚拟机无法解决的严重问题。JVM系统内部错误、资源耗尽等严重情况

不编写针对性代码进行处理。

Exception：其他因编程错误或外在因素导致的一般错误。编译时异常、运行时异常。

## 7.2 异常的分类



![20210104203233353](D:\Learn\Java\笔记\20210104203233353.png)

## 7.3异常处理机制一

过程一：抛：一旦出现异常，在异常代码处生成一个对应异常类的对象。并抛出此对象。抛出后，其后的代码就不执行。

过程二：抓：异常的处理方式

1. **try-catch-finally**

   ```java
   try{
       //可能出现异常的代码
   }catch(异常类型1 变量名1){
       //处理异常方式1
   }catch(异常类型2 变量名2){
       //处理异常方式2
   }catch(异常类型3 变量名3){
       //处理异常方式3
   }
   ······
   finally{
       //一定会执行的代码
   }
   //单元厕所
   package com.atguigu.java;
   import org.junit.Test;
   //异常处理
   public class ExceptionTest1 {
   	@Test
   	public void test1(){
   		String str = "123";
   		str = "abc";
   		try{
   			int num = Integer.parseInt(str);
   			
   			System.out.println("hello---1");
   		}catch (NullPointerException e) {
   			System.out.println("出现空指针异常");
   		}
   		catch(NumberFormatException e){
   			System.out.println("出现数据转换异常");
   		}
   		System.out.println("hello---2");
   		
   	}
   }
   //错误信息
   System.out.println(e.getMessage());
   			e.printStackTrace();
   ```

   **说明：**

   * finally可选，可以不写

     * finally中声明的是一定会执行的代码，即使catch中有return或出现错误
     * finally先执行
     * 数据库连接、输入输出流、网络编程Socket等，JVM不能自动回收，在finally中手动释放
     * try-catch结构可以相互嵌套

   * try可以将出现异常的代码包装起来。生成一个对应异常的对象，在catch中进行匹配

   * 匹配到时，如果没有finally则跳出try-catch结构继续执行后面的程序

   * catch中的异常类型满足子父类关系，则子类必须在父类上面

   * //错误信息

     ```java
     System.out.println(e.getMessage());//得到string然后输出
     e.printStackTrace();直接输出
     ```

   * try中声明的结构在出了try结构以后，不能再被调用

   * 编译时不报错，运行时仍可能报错。

   * 由于运行时异常很常见，不针对其编写try-catch

2. **throws+异常类型**

   写在方法声明后，说明此方法执行后可能会抛出的异常。

   一旦方法体执行时，出现异常，生成对象，后续代码不再执行，抛出异常。

ry-catch-finally处理掉了异常，第二种方法没有处理掉异常。

方法重写规则之一：子类抛出的异常类型不大于父类被重写的方法的异常

**选择：**

1. 如果父类中被重写的方法没有throws，子类中重写的方法必须用try-catch方式处理
2. 方法具有递进关系的用throws。而执行的第一个方法可以考虑try-catch方式处理
3. 可以用两种，但是没必要

## 7.4 手动抛出异常

对象的产生：

* 系统自动生成的异常对象

* 手动生成一个异常对象并抛出（throw）

  ```java
  //手动抛出异常
  throw new RuntimException("您输入的数据非法！")
  ```

## 7.5 用户自定义异常类

如何自定义异常类？

1. 继承于现有异常结构：RuntimException、Exception
2. 提供全局常量：serialVersionUID,唯一标识该类
3. 提供重载的构造器

```java
package exer;

public class EcDef extends Exception{
	static final long serialVersionUID = -3387516993124229948L;
	public EcDef(){
		
	}
	
	public EcDef(String msg){
		super(msg);
	}
}


package exer;

public class EcmDef {
	public static void main(String[] args) {
		try {
			int i = Integer.parseInt(args[0]);
			int j = Integer.parseInt(args[1]);
			int result = ecm(i,j);
			
			System.out.println(result);
		} catch (NumberFormatException e) {
			System.out.println("数据类型不一致");
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("缺少命令行参数");
		} catch (ArithmeticException e) {
			System.out.println("除0");
		} catch (EcDef e) {
			System.out.println(e.getMessage());
		}
	}
	public static int ecm(int i,int j) throws EcDef{
		if(i<0||j<0){
			throw new EcDef("分母或分子负数");
		}
		return i/j;
	}
}

```

